#server:
#  port: ${PORT}

spring:
  application:
    name: Spring Boot Java Project (Consumer)
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: "jdbc:mysql://localhost:3306/imagehub" # JDBC URL of the database
    username: "root" # username and password for Database
    password: "niharika"
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9093

# Reduce logging level
logging:
  level:
    root: warn # log only warning and error

# Custom environment variables
custom:
  image-collection-dir: "/Users/niharika/Workspace/Personal/IntellijProjects/Project ImageHub/photoGallery"
  target-image-resolution-count: 3


# java -jar -DHEIGHT=128 -DWIDTH=128 -DGROUP_ID=group1 ./target/pixprocessor-service-0.0.1-SNAPSHOT.jar
